AWSTemplateFormatVersion : '2010-09-09'
Description: 'Splunk Observability Cloud EventBridge Event Forwarder App'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SplunkObservabilityCloudAccessToken:
    Type: String
    Description: 'Splunk Observability Cloud Access Token. Can be found in the Splunk Observability Cloud --> Settings --> Access Tokens.'
  SplunkObservabilityCloudIngestEndpoint:
    Type: String
    Description: 'Splunk Observability Cloud Ingest Endpoint. Can be found in the Splunk Observability Cloud --> My Profile --> Organizations --> Real-time Data Ingest Endpoint.'
  SplunkObservabilityCloudSendTimeout:
    Type: String
    Default: 1000
    Description: 'Send timeout in milliseconds.'
  EventSources:
    Type: CommaDelimitedList
    Default: 'aws.ec2'
    Description: 'Event sources to forward to the Splunk Observability Cloud. Use comma delimited list for multiple sources, for example: "aws.ec2,aws.s3". Be cautious with using "aws.lambda" (more in README)'

Resources:
  SplunkObservabilityCloudEventBridgeEventsForwarder:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: ./src
      Timeout: 60
      Environment:
        Variables:
          SPLUNK_OBSERVABILITY_CLOUD_ACCESS_TOKEN:
            Ref: SplunkObservabilityCloudAccessToken
          SPLUNK_OBSERVABILITY_CLOUD_ENDPOINT_URL:
            Ref: SplunkObservabilityCloudIngestEndpoint
          SPLUNK_OBSERVABILITY_CLOUD_SEND_TIMEOUT:
            Ref: SplunkObservabilityCloudSendTimeout
      Events:
        CWEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source: !Ref EventSources

# Publishing the App in Serverless application repo:
# sam validate --profile <awsprofile> --template template.yaml --region <region>
# sam package --profile <awsprofile> --s3-bucket <bucket> --region <region> --output-template-file packaged.yaml --template template.yaml
# Use AWS SAM CLI or AWS console to publish the packaged.yaml file.