AWSTemplateFormatVersion : '2010-09-09'
Description: 'Splunk Observability Cloud EventBridge Event Forwarder App - Encrypted token'
Transform: AWS::Serverless-2016-10-31

Parameters:
  EncryptedSplunkObservabilityCloudAccessToken:
    Type: String
    Description: 'Encrypted Splunk Observability Cloud Access Token. The token to encrypt can be found in Splunk Observability Cloud --> Settings --> Access Tokens.'
  SplunkObservabilityCloudIngestEndpoint:
    Type: String
    Description: 'Splunk Observability Cloud Ingest Endpoint. Can be found in the Splunk Observability Cloud --> My Profile --> Organizations --> Real-time Data Ingest Endpoint.'
  SplunkObservabilityCloudSendTimeout:
    Type: String
    Default: 1000
    Description: 'Send timeout in milliseconds.'
  EventSources:
    Type: CommaDelimitedList
    Default: 'aws.ec2'
    Description: 'Event sources to forward to the Splunk Observability Cloud. Use comma delimited list to specify multiple sources, for example: "aws.ec2,aws.s3". Please avoid "aws.kms" as this will lead to an invocation loop. Be cautious with using "aws.lambda" (more in README).'
  KeyId:
    Type: String
    Description: 'Key Id of the key used to encrypt the Splunk Observability Cloud token. Key Id is the last part of the Key ARN.'

Resources:
  SplunkObservabilityCloudEventBridgeEventsForwarder:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: ./src
      Timeout: 60
      Environment:
        Variables:
          ENCRYPTED_SPLUNK_OBSERVABILITY_CLOUD_ACCESS_TOKEN:
            Ref: EncryptedSplunkObservabilityCloudAccessToken
          SPLUNK_OBSERVABILITY_CLOUD_ENDPOINT_URL:
            Ref: SplunkObservabilityCloudIngestEndpoint
          SPLUNK_OBSERVABILITY_CLOUD_SEND_TIMEOUT:
            Ref: SplunkObservabilityCloudSendTimeout
      Events:
        CWEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
               source: !Ref EventSources
      Policies:
        - KMSDecryptPolicy:
            KeyId:
              Ref: KeyId